### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by kaos** [plewto/Cadejo#1]
Thought that maybe we don't want to spam the overtone mailing list with our coding back and forth, and to get better formatting etc, I open an issue, to post what I find etc..

**Comment by kaos** [comment]
Not sure if this helps you at all, but here are the midi events I get from overtone when I press and release C (I think it is only two events, but they get sent down multiple times with a varying args..)

```
cadejo.core=> (overtone.core/event-debug-on)

event:  [:midi :note-on] ({:status :note-on, :note 60, :timestamp 103863463573, :velocity 43, :data1 60, :msg #<FastShortMessage com.sun.media.sound.FastShortMessage@467e06b5>, :device {:sinks 0, :info #<MidiInDeviceInfo Port 1>, :name "Port 1", :overtone.studio.midi/dev-num 0, :version "Unknown version", :device #<MidiInDevice com.sun.media.sound.MidiInDevice@62dcfdf5>, :sources 2147483647, :vendor "Focusrite A.E. Ltd", :transmitter #<MidiInTransmitter com.sun.media.sound.MidiInDevice$MidiInTransmitter@5354210f>, :description "Launchkey 61 Port 1", :overtone.studio.midi/full-device-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}, :channel 0, :command :note-on, :velocity-f 0.33858266, :data2-f 0.33858266, :data2 43, :dev-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}) 

event:  [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0] ({:status :note-on, :note 60, :timestamp 103863463573, :velocity 43, :data1 60, :msg #<FastShortMessage com.sun.media.sound.FastShortMessage@467e06b5>, :device {:sinks 0, :info #<MidiInDeviceInfo Port 1>, :name "Port 1", :overtone.studio.midi/dev-num 0, :version "Unknown version", :device #<MidiInDevice com.sun.media.sound.MidiInDevice@62dcfdf5>, :sources 2147483647, :vendor "Focusrite A.E. Ltd", :transmitter #<MidiInTransmitter com.sun.media.sound.MidiInDevice$MidiInTransmitter@5354210f>, :description "Launchkey 61 Port 1", :overtone.studio.midi/full-device-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}, :channel 0, :command :note-on, :velocity-f 0.33858266, :data2-f 0.33858266, :data2 43, :dev-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}) 

event:  (:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0 :note-on 60) ({:status :note-on, :note 60, :timestamp 103863463573, :velocity 43, :data1 60, :msg #<FastShortMessage com.sun.media.sound.FastShortMessage@467e06b5>, :device {:sinks 0, :info #<MidiInDeviceInfo Port 1>, :name "Port 1", :overtone.studio.midi/dev-num 0, :version "Unknown version", :device #<MidiInDevice com.sun.media.sound.MidiInDevice@62dcfdf5>, :sources 2147483647, :vendor "Focusrite A.E. Ltd", :transmitter #<MidiInTransmitter com.sun.media.sound.MidiInDevice$MidiInTransmitter@5354210f>, :description "Launchkey 61 Port 1", :overtone.studio.midi/full-device-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}, :channel 0, :command :note-on, :velocity-f 0.33858266, :data2-f 0.33858266, :data2 43, :dev-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}) 

event:  (:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0 :note-on) ({:status :note-on, :note 60, :timestamp 103863463573, :velocity 43, :data1 60, :msg #<FastShortMessage com.sun.media.sound.FastShortMessage@467e06b5>, :device {:sinks 0, :info #<MidiInDeviceInfo Port 1>, :name "Port 1", :overtone.studio.midi/dev-num 0, :version "Unknown version", :device #<MidiInDevice com.sun.media.sound.MidiInDevice@62dcfdf5>, :sources 2147483647, :vendor "Focusrite A.E. Ltd", :transmitter #<MidiInTransmitter com.sun.media.sound.MidiInDevice$MidiInTransmitter@5354210f>, :description "Launchkey 61 Port 1", :overtone.studio.midi/full-device-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}, :channel 0, :command :note-on, :velocity-f 0.33858266, :data2-f 0.33858266, :data2 43, :dev-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}) 

event:  [:midi :note-off] ({:status :note-off, :note 60, :timestamp 103864951576, :velocity 67, :data1 60, :msg #<FastShortMessage com.sun.media.sound.FastShortMessage@6cdab1b9>, :device {:sinks 0, :info #<MidiInDeviceInfo Port 1>, :name "Port 1", :overtone.studio.midi/dev-num 0, :version "Unknown version", :device #<MidiInDevice com.sun.media.sound.MidiInDevice@62dcfdf5>, :sources 2147483647, :vendor "Focusrite A.E. Ltd", :transmitter #<MidiInTransmitter com.sun.media.sound.MidiInDevice$MidiInTransmitter@5354210f>, :description "Launchkey 61 Port 1", :overtone.studio.midi/full-device-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}, :channel 0, :command :note-off, :velocity-f 0.52755904, :data2-f 0.52755904, :data2 67, :dev-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}) 

event:  [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0] ({:status :note-off, :note 60, :timestamp 103864951576, :velocity 67, :data1 60, :msg #<FastShortMessage com.sun.media.sound.FastShortMessage@6cdab1b9>, :device {:sinks 0, :info #<MidiInDeviceInfo Port 1>, :name "Port 1", :overtone.studio.midi/dev-num 0, :version "Unknown version", :device #<MidiInDevice com.sun.media.sound.MidiInDevice@62dcfdf5>, :sources 2147483647, :vendor "Focusrite A.E. Ltd", :transmitter #<MidiInTransmitter com.sun.media.sound.MidiInDevice$MidiInTransmitter@5354210f>, :description "Launchkey 61 Port 1", :overtone.studio.midi/full-device-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}, :channel 0, :command :note-off, :velocity-f 0.52755904, :data2-f 0.52755904, :data2 67, :dev-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}) 

event:  (:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0 :note-off 60) ({:status :note-off, :note 60, :timestamp 103864951576, :velocity 67, :data1 60, :msg #<FastShortMessage com.sun.media.sound.FastShortMessage@6cdab1b9>, :device {:sinks 0, :info #<MidiInDeviceInfo Port 1>, :name "Port 1", :overtone.studio.midi/dev-num 0, :version "Unknown version", :device #<MidiInDevice com.sun.media.sound.MidiInDevice@62dcfdf5>, :sources 2147483647, :vendor "Focusrite A.E. Ltd", :transmitter #<MidiInTransmitter com.sun.media.sound.MidiInDevice$MidiInTransmitter@5354210f>, :description "Launchkey 61 Port 1", :overtone.studio.midi/full-device-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}, :channel 0, :command :note-off, :velocity-f 0.52755904, :data2-f 0.52755904, :data2 67, :dev-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}) 

event:  (:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0 :note-off) ({:status :note-off, :note 60, :timestamp 103864951576, :velocity 67, :data1 60, :msg #<FastShortMessage com.sun.media.sound.FastShortMessage@6cdab1b9>, :device {:sinks 0, :info #<MidiInDeviceInfo Port 1>, :name "Port 1", :overtone.studio.midi/dev-num 0, :version "Unknown version", :device #<MidiInDevice com.sun.media.sound.MidiInDevice@62dcfdf5>, :sources 2147483647, :vendor "Focusrite A.E. Ltd", :transmitter #<MidiInTransmitter com.sun.media.sound.MidiInDevice$MidiInTransmitter@5354210f>, :description "Launchkey 61 Port 1", :overtone.studio.midi/full-device-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}, :channel 0, :command :note-off, :velocity-f 0.52755904, :data2-f 0.52755904, :data2 67, :dev-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]}) 
```

This worked when I had just booted Cadejo, but before I had pressed the button to start a server. After that, there were no more events coming in to overtone from the Launchkey.

Tried both Default and Internal, with same result.

**Comment by kaos** [comment]
I do get MIDI info in the parent window to the virtual keyboard..
![image](https://cloud.githubusercontent.com/assets/72965/12728615/fa6f635a-c922-11e5-81e6-7a85a207509f.png)

**Comment by plewto** [comment]
Great, thanks.

I am at work right now, I will take a look at this about midnight my time.

**Comment by plewto** [comment]
I’m not too sure how the event trace you posted were generated. I see  2 events, a note-on and corresponding off. It looks like each event is being reported 4 times, I think we can ignore that. 

Also can we eliminate any “down stream” problems?   In other words once an instrument is loaded does the virtual keyboard produce audio? 

I notice too a discrepancy between the MIDI port name in your screenshot and what I’m getting.  On yours the device name is “Port 1” whereas on mine, the name is an actual device.  But maybe “Port 1” is the device? I don’t know.  I have two other MIDI interfaces I can try to see what the their names look like (they’re in storage so I can check them immediately).  Are there any other MIDI interfaces you can try to see if they behave differently from the launchkey? 

![screenshot_2016-02-02_00-37-29](https://cloud.githubusercontent.com/assets/4853654/12742407/ffa3005c-c94a-11e5-93a0-8f5ba6555ac6.png)

**Comment by kaos** [comment]
Thanks, my turn to be at work now, but I'll dig some deeper tonight, try to find why the events from overtone stops coming, unless you beat me to it ;)

**Comment by kaos** [comment]
The event trace was generated by issuing this command: `(overtone.core/event-debug-on)`

And yes I agree regarding that there is likely no downstream issues, once the events gets in, it should work, as I do get sound using the virtual keyboard.

**Comment by kaos** [comment]
This is what overtone thinks of my device:

```
cadejo.core=> (overtone.core/midi-connected-devices)
({:sinks 0, :info #<MidiInDeviceInfo Port 1>, :name "Port 1", :overtone.studio.midi/dev-num 0, :version "Unknown version", :device #<MidiInDevice com.sun.media.sound.MidiInDevice@36db839d>, :sources 2147483647, :vendor "Focusrite A.E. Ltd", :description "Launchkey 61 Port 1", :overtone.studio.midi/full-device-key [:midi-device "Focusrite A.E. Ltd" "Port 1" "Launchkey 61 Port 1" 0]} {:sinks 0, :info #<MidiInDeviceInfo Launchkey InControl>, :name "Launchkey InControl", :overtone.studio.midi/dev-num 0, :version "Unknown version", :device #<MidiInDevice com.sun.media.sound.MidiInDevice@5104f2de>, :sources 2147483647, :vendor "Focusrite A.E. Ltd", :description "Launchkey 61 Launchkey InControl", :overtone.studio.midi/full-device-key [:midi-device "Focusrite A.E. Ltd" "Launchkey InControl" "Launchkey 61 Launchkey InControl" 0]})
```

**Comment by kaos** [comment]
Sorry, this is the only MIDI device I have to try with.. :/

**Comment by plewto** [comment]
I just pushed minor changes to the debug branch.

Turn the overtone event-debug-off and see if Cadjeo reports anything.

We are looking to see if the input-port is receiving active-sensing events.  I had them filtered out previously to reduce screen clutter.    Most devices transmit active-sensing messages several times a second, it's the MIDI equivalent of "ping".     On my machine as soon as I connect a MIDI device the terminal starts spitting out an endless stream of the following trace lines, you should be getting something similer

;; --> [0] InputPort status :active-sensing command null chan 14 data1  0  data2  0

Its possible the launchkey does not transmit active-sensing, well have to look that up but most devices do.

**Comment by plewto** [comment]
Active sensing may not tell us anything. I just realized the active sensing events I see are being generated by the keyboard (A Yamaha SY35)  and not by the MIDI adapter (some kind of Emu thing) it is plugged into.  I took a quick look at the lauchkey MIDI implementation chart and I didn't see anything about active-sensing.

**Comment by kaos** [comment]
No, you were right. I don't see any active sensing events..

**Comment by kaos** [comment]
Ah, I think I figured out what/when the connection to my Launchkey is lost.

It seems to be the `open/close` operation in `cadejo.util.midi/transmitters`: https://github.com/plewto/Cadejo/blob/master/src/cadejo/util/midi.clj#L45

Since I see the overtone events initially, but if I then call `(cadejo.util.midi/list-midi-info)` it stops.

I'll have a stab at getting the list from overtone instead of directly from the java libs.. as the info is already available there..

EDIT: I must admit it does take me some time wrapping my head around the clojure syntax.. :p

**Comment by kaos** [comment]
Yay, I got it workin'!!

```
;; -->[0] InputPort status :note-off command :note-off chan  0 data1  57 data2  12

;; -->[0] InputPort status :note-on command :note-on chan  0 data1  55 data2   2

;; -->[0] InputPort status :note-off command :note-off chan  0 data1  55 data2  29

;; -->[0] InputPort status :note-on command :note-on chan  0 data1  59 data2  26

;; -->[0] InputPort status :note-off command :note-off chan  0 data1  59 data2  59

;; -->[0] InputPort status :note-on command :note-on chan  0 data1  59 data2  17

;; -->[0] InputPort status :note-off command :note-off chan  0 data1  59 data2  40

;; -->[0] InputPort status :note-on command :note-on chan  0 data1  57 data2  17

;; -->[0] InputPort status :note-off command :note-off chan  0 data1  57 data2  36

;; -->[0] InputPort status :note-on command :note-on chan  0 data1  55 data2  15

;; -->[0] InputPort status :note-off command :note-off chan  0 data1  55 data2  34
```

Thank you so much for your support Steve. I'll send a pull requests just to show what I did. I also think I spotted your mistake that would probably have worked right away too.. (you used hw-name as dev when connecting, which was empty..).

**Comment by plewto** [comment]
Ah! I was wondering if I had done that.

**Comment by plewto** [comment]
Ergh! I hate to say it but bad news, it didn't work on this end.  When I attempt to connect a MIDI device I get an IllegalArgumentException with the following message 
" Did not find a matching midi input device for: E2x2 [hw:2,0,0]"

The stack trace was
cadejo.ui.midi.scene-editor/create-midi-panel (line 163)
    cadejo.midi.input-port/midi-input-port (line 220)
          cadejo.midi.input-port/midi-input-port (line 211)

I haven't looked into this yet but I think we have to reconcile expected device names between Mac and Linux.  (For the moment I'm going to ignore victims of Windows but eventually want to bring them into the fold too).

Another, more ugly, approach would be some sort of test to select the device based on the underlying OS. 

I do like the idea of using overtone.midi instead of the java libraries.

**Comment by kaos** [comment]
what about the UI selection dialog from overtone.midi?

According to the [comments](https://github.com/overtone/midi-clj/blob/master/src/overtone/midi.clj#L131) if not device is passed as argument, you'd get a dialog with a list of devices to choose from..

**Comment by kaos** [comment]
What does your list of connected devices look like?
`(overtone.core/midi-connected-devices)`

**Comment by plewto** [comment]
I think I see what can be done..   

1) change the input-port constructor to take the device directly, instead of the device name.
2) modify the "connect button" ActtionListener in the scene-editor accordingly. 

At the moment I'm not on a machine where I can make these edits, I will try later this afternoon.

**Comment by plewto** [comment]
I have not been having any luck at all, I keep getting a NullPointerException I have been unable to trace down. 

The message in the last commit spells out where the issues are.

**Comment by kaos** [comment]
Do you also get these when starting the repl.. ?

```
WARNING: complement already refers to: #'clojure.core/complement in namespace: sgwr.util.color, being replaced by: #'sgwr.util.color/complement
Warning: protocol #'sgwr.components.component/SgwrComponent is overwriting function contains?
WARNING: contains? already refers to: #'clojure.core/contains? in namespace: sgwr.components.component, being replaced by: #'sgwr.components.component/contains?
```

**Comment by kaos** [comment]
Got a fix in #4. See if it works for you on Linux..

**Comment by plewto** [comment]
I think thats it!  Thanks.
Im off to work so can t spend a lot of time, I did a real quick test and it seems to work!

**Comment by plewto** [comment]
Everything looks great.   I have cleaned up the code and merged the changes into the master.  Again thanks so much for your help.

The compiler warnings are generated in response to reassigning names of standard Clojure functions and are nothing to worry about.  For instance “complement” is a standard Clojure function which returns the complement of a function.   A warning is generated because sgwr.util.color defines a function by the same name which returns the complement of a color.  

If there is a potential conflict you can get the desired function by using its full name clojure.core/complement or sgwr.color.util/complement.

**Comment by kaos** [comment]
Great, thanks. I'm looking forward to play around and get to know Cadejo better, now that I get proper sound out of it :)

Would like to add device specific support, too.. like detecting which device you have connected, you can select knobs and sliders for controls to an instrument, instead of just the cc numbers..
Would also like to get feedback on the instrument page somewhere (on the CTRL page, most likely) with the current value for the controls from the device, so you get live feedback what is changing when you turn a knob.

Would also be great to be able to utilize the play/stop/record.. etc buttons, and the launchpad and incontrol features, etc etc.. the list can be made rather long ;)

I've started looking at the overall design of cadejo and the instruments etc. I'm really impressed with what you've managed to implement. Would most likely need a few pointers and ideas for what I want to do, but lets take that as they come... (I'll open separate issues to discuss each feature in isolation, see how much time and energy I can muster for all I'd like to have; and so it is features that you'd like to see in cadejo, too.. ;)
